image: node:lts

cache:
  key: none
  paths:
    - .yarn
    - node_modules
    - dist

stages:
  - build
  - test
  - sentry
  - deploy

before_script:
  - yarn global add @nrwl/cli @angular/cli --cache-folder .yarn
  - yarn install --pure-lockfile --cache-folder .yarn
  - sed -ri s/\'VERSION\'/\'$CI_COMMIT_SHA\'/ apps/tokkify/src/environments/environment.prod.ts

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - git checkout -B master origin/master
    - |
      nx affected:build --prod
  artifacts:
    paths:
      - dist

lint:
  stage: test
  variables:
    GIT_STRATEGY: clone
  script:
    - git checkout -B master origin/master
    - |
      nx affected:lint

test:
  stage: test
  variables:
    GIT_STRATEGY: clone
  script:
    - git checkout -B master origin/master
    - |
      nx affected:test --code-coverage
      bash <(curl -s https://codecov.io/bash)

e2e:
  image: cypress/base:12
  stage: test
  variables:
    GIT_STRATEGY: clone
  script:
    - git checkout -B master origin/master
    - |
      nx affected:e2e

deploy:
  cache:
    key: none1
  before_script:
    - echo 'before script'
  stage: deploy
  only:
    refs:
      - master
  script:
    - |
      yarn global add firebase-tools
      firebase deploy --project tokkify-song-requests --token $FIREBASE_TOKEN

sentry_job:
  cache:
    key: none1
  before_script:
    - echo 'before script'
  only:
    refs:
      - master
  stage: sentry
  image: getsentry/sentry-cli
  script:
    - echo "Create a new release $CI_COMMIT_SHA"
    #- export SENTRY_URL=$SENTRY_BASE_URL
    - export SENTRY_AUTH_TOKEN=$SENTRY_BASE_TOKEN
    - export SENTRY_ORG=$SENTRY_BASE_ORGANIZATION
    - export SENTRY_PROJECT=$SENTRY_BASE_PROJECT
    - sentry-cli releases new $CI_COMMIT_SHA
    - sentry-cli releases set-commits --auto $CI_COMMIT_SHA
    - sentry-cli releases files $CI_COMMIT_SHA upload-sourcemaps $CI_PROJECT_DIR/dist/apps/tokkify -x .js -x .map --validate --verbose --rewrite --strip-common-prefix
    - sentry-cli releases finalize $CI_COMMIT_SHA
    - echo "Finalized release for $CI_COMMIT_SHA"
